version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/manage/data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/k11b303.p.ssafy.io/fullchain.pem:/etc/letsencrypt/live/k11b303.p.ssafy.io/fullchain.pem
      - /etc/letsencrypt/live/k11b303.p.ssafy.io/privkey.pem:/etc/letsencrypt/live/k11b303.p.ssafy.io/privkey.pem
    networks:
      - service_local

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper-container
    networks:
      - service_local
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  
    networks:
      - service_local
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - service_local
    volumes:
      - /home/ubuntu/service/data/redis/data:/data 
      - /home/ubuntu/service/data/redis/redis.conf:/redis.conf
    command: redis-server /redis.conf
    sysctls:
      - net.core.somaxconn=1024


networks:
  service_local:
    external: true