version: '3.8'

services:
  # mongos
  mongos:
    container_name: mongos
    image: mongo
    restart: always
    ports:
      - 0.0.0.0:60001:27017
    command: mongos --configdb configReplica/config1:27017,config2:27017,config3:27017 --bind_ip 0.0.0.0 --port 27017
    networks : 
      - service_local


networks:
  service_local:
    external: true